---
- hosts: server.domain.com
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    validate_certs: false
    ansible_winrm_kerberos_delegation: true
    ansible_become: false
    
  tasks:
        
    - name: Add server to specific Centrify group
      script: files/add.AD.ps1 {{hostname}}
      vars:
        become: yes
      register: output
      ignore_errors: True
      
    - debug: var=output
      